# Generated by Django 4.2.4 on 2023-09-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Producto')),
                ('size', models.CharField(max_length=100, verbose_name='Talla')),
                ('image', models.ImageField(upload_to='services', verbose_name='imagen')),
                ('price', models.TextField(verbose_name='Precio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Compras',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
