# Generated by Django 4.2.4 on 2023-09-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Precio'),
        ),
    ]
